### ISSUE TITLE
getting 500 timeout

### ISSUE THREAD

**Issue by Chow-ai** [johnolafenwa/DeepStack#105]
I was getting the 500 timeout response, when running the gpu docker container (ubuntu).
I noticed the IP address for your telemetry server had changed, so altered the firewall for that, still no luck.
Pulled the latest update (updated 6 days ago), and still no luck.
Any suggestions?

Also is the IP of the telemetry server likely to change frequently, as it causes problems for the firewall.

Thanks

**Comment by spammenotinoz** [comment]
Unsure if it's related but perhaps your GPU is too new.  Deepstack only supports older GPU's that work with CUDA 10.1.

**Comment by Chow-ai** [comment]
I had missed that. Thanks. That explains the problem.
