### ISSUE TITLE
Incorrect face boxes in face/recognize endpoint

### ISSUE THREAD

**Issue by dataGAI** [johnolafenwa/DeepStack#106]
When I try to recognize multiple faces in the image with` v1/vision/face/recognize` endpoint it returns incorrect face boxes. 
To reproduce this bug no faces should be registered in deepstack.
In my opinion, this bug occurs due to misspelling in https://github.com/johnolafenwa/DeepStack/blob/dev/intelligencelayer/shared/face.py#L348

**Comment by OlafenwaMoses** [comment]
Thanks @dataGAI . Fixed in #116
