### ISSUE TITLE
Download not available Windows 10 CPU version

### ISSUE THREAD

**Issue by iamkyoumei** [johnolafenwa/DeepStack#109]
Hello, for some reason the download for the latest release of Windows 10 CPU version is showing this error;

`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>ServiceUnavailable</Code>
<Message>Service is unavailable at this time.</Message>
</Error>`

It seems this link is broken..

`https://deepquest.sfo2.digitaloceanspaces.com/deepstack/DeepStack-Installer-CPU-2021.02.1.exe`

Does anyone know where I can access this download?

https://github.com/johnolafenwa/DeepStack/releases/tag/0.3-beta

**Comment by OlafenwaMoses** [comment]
@kyoumei Apologies for the broken link. Please refer to the page below for the latest version of DeepStack for Windows 10 (CPU and GPU)

https://docs.deepstack.cc/windows/

**Comment by githubDiversity** [comment]
the 2021.2 windows version seems to not be interoperable with Blue Iris when running side by side.
I have noticed that the docker version is now 2021.>2

@OlafenwaMoses @johnolafenwa is this intentional? Are you dropping native windows support?

Anyhow, may I please ask for the location of the debugging log? for both docker or windows

**Comment by githubDiversity** [comment]
@OlafenwaMoses @johnolafenwa May I also please ask for build instructions for the native windows build target since it seems logging and master branch features seem to be missing for download.

**Comment by johnolafenwa** [comment]
Hello @githubDiversity Find here https://docs.deepstack.cc/windows/index.html up to date instructions for running DeepStack with all the features in the main branch. Note, DeepStack is now on a montly release cadence for both Docker and Windows versions and you will see more frequent updates.

**Comment by soubhik-khan** [comment]
Hi, looks like windows CPU and GPU both the download links are broken on this page - https://docs.deepstack.cc/windows/index.html#install-deepstack-gpu
![Screen Shot 2022-09-22 at 12 24 39 PM](https://user-images.githubusercontent.com/16430033/191834135-3dc98a00-c0ab-444c-bd8f-83165e3c3d3f.png)

Am I looking at the wrong place? Can anyone share a working download link?

**Comment by squeaky-geek** [comment]
> Hi, looks like windows CPU and GPU both the download links are broken on this page - https://docs.deepstack.cc/windows/index.html#install-deepstack-gpu ![Screen Shot 2022-09-22 at 12 24 39 PM](https://user-images.githubusercontent.com/16430033/191834135-3dc98a00-c0ab-444c-bd8f-83165e3c3d3f.png)
> 
> Am I looking at the wrong place? Can anyone share a working download link?

same for me  shows an xml error

**Comment by FredrikNas** [comment]
Same here, both CPU and GPU links are broken on the hosts site!

**Comment by githubDiversity** [comment]
I can't be sure as I have not checked in for a while now but I think this project, however much potential it has, is not getting the love it deserves.
@johnolafenwa I will fully understand it if there is just so many other things that keep you from developing this masterpiece.
And of course if I am speaking out of line now and things are shaping up real well then please accept my apology. I have not really diven into the current state of the code for some time now.

**Comment by florisvangeel** [comment]
all these zip files are gone, the whole deepquest bucket is suspended.
Does anyone have them from before and is willing to share with us?

**Comment by githubDiversity** [comment]
currently not in my office as on holliday. I might havvve something 
laying around.

**Comment by kyoumei** [comment]
> all these zip files are gone, the whole deepquest bucket is suspended. Does anyone have them from before and is willing to share with us?

I don't use DeepStack anymore (I use CodeProject AI now), but you're not able to download it from the repo releases?

https://github.com/johnolafenwa/DeepStack/releases
