### ISSUE TITLE
Annotated Images used for DeepStack Object Detection API?

### ISSUE THREAD

**Issue by BeanBagKing** [johnolafenwa/DeepStack#125]
I'm interested in training a more specific custom data set, but would like to use some categories of DeepStack as a basis. Is there an annotated image set that was used to train DeepStack's Object Detection API, and would you be able to share it?

**Comment by OlafenwaMoses** [comment]
DeepStack's object detection API was trained on the COCO dataset. You can download it from the link below and extract images for the classes you want to work with.

https://cocodataset.org/#home
