### ISSUE TITLE
DeepStack-Security-Camera-Models

### ISSUE THREAD

**Issue by MikeLud** [johnolafenwa/DeepStack#131]
I created several custom model that are for security cameras. I removed objects that are not needed for security cameras and added some additional animals. Also there is a license plate model to use with a LPR camera. The models are still a work in progress. These models were all trained using yolov5s.pt. The accuracy of the models are equal to if not better then yolov5m.pt along with faster.

link to a GitHub repository: 
https://github.com/MikeLud/DeepStack-Security-Camera-Models

**Comment by OlafenwaMoses** [comment]
This is an awesome work @MikeLud. We are really happy to see the effort and collaboration that made this possible. 

We will add this project to our custom models sample page ( https://docs.deepstack.cc/custom-models-samples/ ) soon.

**Comment by MikeLud** [comment]
@OlafenwaMoses I am working two Python scripts to use with Blue Iris and DeepStack that will do full OCR on the license plates

![image](https://user-images.githubusercontent.com/36526272/147890583-177373a5-6184-49fb-8dc3-165b034feda8.png)

**Comment by OlafenwaMoses** [comment]
@MikeLud PR out to add this model to the Custom-Model-Sample page of the documentation.

https://github.com/johnolafenwa/deepstack-docs/pull/60
