### ISSUE TITLE
ssl cert path for https

### ISSUE THREAD

**Issue by t3therdev** [johnolafenwa/DeepStack#134]
We are starting to checkout deepstack and impressed so far. however when testing on windows for example we see that in server.go there is a stringvar for --CERT-PATH. 

We are looking for a way to use SSL with deepstack when using windows. Can you advise why we are getting "flag provided but no defined"  It seems its not available in the compile windows build?

Can you provide an example of how to use a server crt and key for doing ssl? Or how ssl would be enabled and the certificate requirements?

If /cert in the root of the deepstack install can be used can you advise what cert names/types are required?

**Comment by OlafenwaMoses** [comment]
Hi @t3therdev , glad to know you are impressed using DeepStack. The support for SSL has been merged but the binary is yet to be released. We will publish a January release soon across all versions of DeepStack and it will include SSL support + other new features. It will also be documented here https://docs.deepstack.cc

**Comment by OlafenwaMoses** [comment]
@t3therdev The latest binaries with version **2022.01.1** are out and now support HTTPS. Visit the documentation link below to learn more.

https://docs.deepstack.cc/ssl/

**Comment by t3therdev** [comment]
Thanks @OlafenwaMoses , when will the new release be available on github? Or for download?

**Comment by OlafenwaMoses** [comment]
@t3therdev Simply pull the latest Docker images or the ones with tags `2022.01.1` or download the Windows binaries from the documentation linked below

https://docs.deepstack.cc
