### ISSUE TITLE
Windows logging / log location

### ISSUE THREAD

**Issue by t3therdev** [johnolafenwa/DeepStack#137]
Using the windows cpu version. Where are logs kept? Per the docker instructions they are located in /root but for windows I do not see any logs for the server. Is there a way to enable logging and where the logs are located? Can you advise more on the logging for windows.

**Comment by johnolafenwa** [comment]
Hello @t3therdev , logs on windows can be found at ```C:/DeepStack/logs```

**Comment by t3therdev** [comment]
Ok, is there a way to enable debug logs or any options for logs?

**Comment by t3therdev** [comment]
I do NOT see that folder on windows.

**Comment by t3therdev** [comment]
the only reference to logs is C:\DeepStack\redis\logs but its not anything to do with detection.
