### ISSUE TITLE
SSL certs expired

### ISSUE THREAD

**Issue by reddoxster** [johnolafenwa/DeepStack#152]
Thought I'd drop a note here since the SSL certs on the main website & the docs appear to have expired (29 Jan, and 31 Jan) & threw a warning on my Firefox desktop on mac.

Expiry: Sat, 29 Jan 2022 11:01:07 GMT

**Comment by OlafenwaMoses** [comment]
Fixed. Thanks @reddoxster

**Comment by remotenw** [comment]
Cents appear to have expired again
