### ISSUE TITLE
DeepStack stop working ! Python.exe get killed!

### ISSUE THREAD

**Issue by jeremypsl** [johnolafenwa/DeepStack#169]
Hello

I run BlueIris 5.5.7.8 and DeepStack 2021.09.1.
Sometimes, i don’t understand why, python.exe get killed and DS don’t work anymore.
I tried to restart it in BI settings : i see the process growing in ram and desapear again…
The only way to get it back is to restart the computer.
I don’t know what is the problem, is there log somewhere i can try to understand what is going wrong ?
This morning, even if i restart the computer, no python.exe in the process…

Thanks.

**Comment by Tinbum1** [comment]
https://github.com/johnolafenwa/DeepStack/issues/167
