### ISSUE TITLE
/v1/vision/face/register dont work on Windows GPU version 

### ISSUE THREAD

**Issue by odd86** [johnolafenwa/DeepStack#53]
Hello, What a fantastic product!

I`m having issues with the GPU version for windows when it comes to register new faces.
I would love to give som logs but what happens is that the endpoint gets called, and thats that (looks like it hangs)

I`m using/testing the exact same code with docker:latest and docker:x5-cpu and there it works

Sometimes deepstack hangs on Docker aswell and needs a restart, looks for me like its stuck in a loop on one image.
Would it be a thing to ad timeout for the endpoints?

**Comment by OlafenwaMoses** [comment]
@odd86 You can find error logs in file located in **C:\Users\<your_windows_username>\AppData\Local\DeepStack\logs\stderr.txt**. 

Find this file and share the logs contained.

**Comment by odd86** [comment]
@OlafenwaMoses - Hello, was nothing in the logs but I figured out what was the problem.

I’m making a system for face recognition and sometimes need to merge an unknown face into a known face (since it is the same person) in that process some of the images that my script makes is 0bytes (don’t know why) but deepstack should check input and just throw an error or ignore files it doesn’t support. When I upload my .jpg that are 0bytes deepstack hangs forever and runs on 35% of my CPU (AMD 5950x)

I made a solution where I check files before I register face, but maybe an error would be good for other users experiencing deepstack "hangs". My guess its a faulty image in most cases

**Comment by odd86** [comment]
@OlafenwaMoses I still have this issue and finaly i found the logs:

Process Process-2:
Traceback (most recent call last):
  File "C:\DeepStack\intelligencelayer\shared\face.py", line 186, in face
    det = detector.predict(img, 0.55)
UnboundLocalError: local variable 'img' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\DeepStack\intelligencelayer\shared\face.py", line 253, in face
    except UnidentifiedImageError:
NameError: name 'UnidentifiedImageError' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\process.py", line 297, in _bootstrap
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\process.py", line 99, in run
  File "C:\DeepStack\intelligencelayer\shared\face.py", line 274, in face
    SharedOptions.db.set(req_id, json.dumps(output))
UnboundLocalError: local variable 'output' referenced before assignment

**Comment by johnolafenwa** [comment]
Thanks for reporting this @odd86 , this will be fixed in the next update.

**Comment by johnolafenwa** [comment]
@odd86 , this has been fixed here https://forum.deepstack.cc/t/deepstack-february-2021-release-fixes-for-jetson-windows-native-and-docker-versions/724
