### ISSUE TITLE
Mode switch doesnt work with Windows 2020.12.beta

### ISSUE THREAD

**Issue by VorlonCD** [johnolafenwa/DeepStack#54]
I tried with both CPU and GPU versions:

`C:\DeepStack>deepstack.exe --VISION-DETECTION True --MODE High --PORT 88`
`flag provided but not defined: -MODE`

I also tried --MODE=High, --MODE and --mode

From the looks of **shared.py**, I can just use `SET MODE=High` at a command prompt before running the EXE?

I didnt see the source for deepstack.exe in this repository?

**Comment by johnolafenwa** [comment]
This is a bug and will be resolved in a new update this week.

**Comment by johnolafenwa** [comment]
@VorlonCD This has been fixed in the latest release https://github.com/johnolafenwa/DeepStack/releases/tag/0.2-beta

**Comment by VorlonCD** [comment]
Great!!
