### ISSUE TITLE
Add another Blue Iris integration to readme.md

### ISSUE THREAD

**Issue by neilenns** [johnolafenwa/DeepStack#55]
Is it possible to add my Blue Iris integration of Deepstack to the readme? It's an alternate approach to the one currently listed that relies on a Docker stack instead of desktop UI and offers quite a bit more customization/options: https://github.com/danecreekphotography/node-deepstackai-trigger

Thanks!

**Comment by OlafenwaMoses** [comment]
Thanks for sharing this @danecreekphotography . We have a [PR](https://github.com/johnolafenwa/DeepStack/pull/56) out to add this integration to the README. 

Also, we have updated the Windows version to a non-UI installation and it is available for CPU and GPU. 
Learn more in DeepStack's updated documentation https://docs.deepstack.cc/windows/

**Comment by robmarkcole** [comment]
merged, thanks @danecreekphotography !

**Comment by neilenns** [comment]
Thanks!
