### ISSUE TITLE
passing `min_confidence` of zero (0) will cause Deepstack to hang indefinitely 

### ISSUE THREAD

**Issue by robmarkcole** [johnolafenwa/DeepStack#58]
As reported in https://github.com/robmarkcole/HASS-Deepstack-object/issues/169 and in my own experience, passing `min_confidence` of zero (0) will cause Deepstack to hang indefinitely. Technically a min confidence of zero is meaningless anyways. We should coerce values to a min confidence of 1%

**Comment by johnolafenwa** [comment]
Thank you @robmarkcole . Please make a PR to address this, files concern are here https://github.com/johnolafenwa/DeepStack/tree/dev/deepstack/intelligencelayer/shared,

**Comment by robmarkcole** [comment]
@johnolafenwa could the issue be in `non_max_suppression()`? This is not easy to debug without understanding what that is performing. 

I see however that `conf_thres=0.1` so we could just pin this at the go endpoint like this?
```go
if val < 0.1 {

response := response.ErrorResponse{Success: false, Error: "min_confidence cannot be less than 0.1"}

c.JSON(400, response)
c.Abort()
return
```

**Comment by robmarkcole** [comment]
I believe this is an example of what non_max_suppression tries to address?

![image](https://user-images.githubusercontent.com/11855322/105621865-f7c92700-5e03-11eb-9389-5f8678ab869e.png)

**Comment by johnolafenwa** [comment]
This has been fixed here https://forum.deepstack.cc/t/deepstack-february-2021-release-fixes-for-jetson-windows-native-and-docker-versions/724
