### ISSUE TITLE
Model sharing

### ISSUE THREAD

**Issue by odd86** [johnolafenwa/DeepStack#59]
Hello, i made a model to get licence plates from cars so its ready to be used for OCR
On my 50 picture test it found 48 plates (many hard pictures i had never thouth it would get).

How can i share this .pt file with other deepstack users that needs to get licenceplates?

**Comment by OlafenwaMoses** [comment]
@odd86 Thank you very much for posting this. We currently don't have a trained model sharing platform yet. However, you can share the model using any of the options below:

- (Option 1)  Upload the trained model to Google Drive/a GitHub release and make a post in https://forum.deepstack.cc with details on using the model, the model type and link to the **.pt** file. With your permission, we can transform this to a full article on the [DeepQuest AI blog](https://medium.com/deepquestai). 

- (Option 2) Write an article or tutorial on the model you trained detailing training, dataset used, link to the **.pt** file and how to run it with DeepStack.

**Comment by odd86** [comment]
@OlafenwaMoses I will make a step-by-step guide for it! Its nice with custom models and maybe we can make a section in the forum for it? I`m currently using deepstack and pytessaact and building a system for home-cam automation with push notifications and a frontend for merging/adding new people and cars. I will come back with the source code for it when I have cleaned up the code and made it easy to run. 

I must say i find the work you and your team are doing inspiring! and if it wasn’t for deepstack non of this would have been made since the learning curve would started to high up!

**Comment by odd86** [comment]
Actualy you guide here: https://docs.deepstack.cc/custom-models/datasetprep/index.html is very accurate.
The only thing i needed to figure out myself was some of the commands in colab:

After i installed the deepstack trainer, the command:
`unzip my-dataset.zip -d my-dataset `
dont work, so i need to do it like this:

add new code line and run:
```
import zipfile
with zipfile.ZipFile('/content/my-dataset.zip.zip', 'r') as zip_ref:
    zip_ref.extractall(/content/my-dataset)
```

and on this command:
`!python3 train.py --dataset-path "my-dataset"`

I needed to add:
`!python3 train.py --dataset-path "/content/my-dataset"`


So except those small things, the toturial you have is quite good!

**Comment by OlafenwaMoses** [comment]
We are glad you find DeepStack really useful and easy to use for your AI-driven home-cam automation. 

We do appreciate the ingenuity you are putting to implement this incredible and intelligence setup. The global technology and IoT community needs more like it. 

Once you have the article ready, feel free to drop the link here and especially on the [DeepStack Forum](https://forum.deepstack.cc/).

**Comment by odd86** [comment]
I just have one question that I’m really wondering about.
For face recognition, what is best in these 2 scenarios:

For training:
1. The whole picture
2. The Person
3. The Face

For recognition:
1. The whole picture
2. The Person
3. The Face

| The whole picture  | The Person | The Face |
| ------------- | ------------- | ------------- |
|<img src="https://user-images.githubusercontent.com/7629853/103805016-44b2ac80-5053-11eb-9c6d-a1c85a7109a2.png" width="200">|<img src="https://user-images.githubusercontent.com/7629853/103804768-e8e82380-5052-11eb-8b68-2f247c9a8e1e.png" width="200">|<img src="https://user-images.githubusercontent.com/7629853/103805076-60b64e00-5053-11eb-9292-9fa6064370f9.png" width="200">|

**Comment by OlafenwaMoses** [comment]
Any of the images will work for both scenarios as DeepStack will automatically crop the face out of the picture before running face registration/recognition.

**Comment by odd86** [comment]
Would more images of a person get you higher confidence?
Rigth now im using 75 images, but often it detects me as unknown

**Comment by robmarkcole** [comment]
@OlafenwaMoses I think it would be great to have a page on the documentation for models contributed by the community. We would have an index and a short description of the model, and overview of the training data, and a link to any code/repo. We could also host the model in an LFS repo. Any thoughts?

**Comment by odd86** [comment]
I can upload the model and the data to a github repo together with an explanation on how to get it working

**Comment by odd86** [comment]
Then i added the repo with some instructions:
[deepstack licenceplate model](https://github.com/odd86/deepstack_licenceplate_model)

**Comment by OlafenwaMoses** [comment]
> Would more images of a person get you higher confidence?
> Rigth now im using 75 images, but often it detects me as unknown

Using tens of images does facilitate higher confidence. However, it is important that the images are diverse to cater for multiple lighting conditions and perspectives.

**Comment by OlafenwaMoses** [comment]
> @OlafenwaMoses I think it would be great to have a page on the documentation for models contributed by the community. We would have an index and a short description of the model, and overview of the training data, and a link to any code/repo. We could also host the model in an LFS repo. Any thoughts?

That sounds really good. In addition to this, we plan on listing the community trained models on DeepStack's Dev Center ( https://dev.deepstack.cc/ ). The purpose of the Dev Center is to provide overview and links to all of DeepStack's resources in the community such as the documentations, integrations, articles, trained models and projects built on DeepStack.

**Comment by OlafenwaMoses** [comment]
> Then i added the repo with some instructions:
> [deepstack licenceplate model](https://github.com/odd86/deepstack_licenceplate_model)

This is perfect @odd86 . Thank you for setting this up so fast and sharing with the community. We will include this in DeepStack's documentation, Dev Center and publications.

**Comment by OlafenwaMoses** [comment]
cc: @johnolafenwa

**Comment by odd86** [comment]
@OlafenwaMoses Happy to help! Also think some of the questions i have gotten answers from you about here should be listet someplace since i think that theese are FAQ`s deepstack users will have :)

**Comment by OlafenwaMoses** [comment]
That will be great. We will setup a Developer FAQ in the documentation. Thanks for the suggestions @odd86

**Comment by OlafenwaMoses** [comment]
@odd86 Developer FAQ now available.

https://docs.deepstack.cc/faq/

Also list of custom models

https://docs.deepstack.cc/custom-models-samples/

**Comment by OlafenwaMoses** [comment]
> @OlafenwaMoses I think it would be great to have a page on the documentation for models contributed by the community. We would have an index and a short description of the model, and overview of the training data, and a link to any code/repo. We could also host the model in an LFS repo. Any thoughts?

Done. Thanks very much @robmarkcole 

https://docs.deepstack.cc/custom-models-samples/

**Comment by manalishi70** [comment]
> Would more images of a person get you higher confidence? Rigth now im using 75 images, but often it detects me as unknown

@odd86 : I have a similar behavior. Do you have any additional experience in training faces you can share?

**Comment by manalishi70** [comment]
> Using tens of images does facilitate higher confidence. However, it is important that the images are diverse to cater for multiple lighting conditions and perspectives.
@OlafenwaMoses: I registered just one userid with 30 images. Faces of the person on the images are from different viewpoints. Images are taken in darker and lighter environment. When I run a recognition with exactly the same faces. Confidence is between 0.5 and 0.72. I put 2 unregistered persons inbetween and recognition shows similar confidence values.
Is this the expected behavior or did I chosse images for registration which are too different?
