### ISSUE TITLE
DeepStack Windows Beta 2 - GPU version is CPU

### ISSUE THREAD

**Issue by VorlonCD** [johnolafenwa/DeepStack#62]
I installed the new GPU beta 2 version and start 4 instances, and send them all a bunch of images to process.

If you watch GPU ram and CPU usage in Task Manager or Process Hacker as they load and run almost no GPU is being used.  

But CPU usage spikes like crazy.    So I think somehow platform.json > server.go, is not correctly setting the mode?

**Comment by VorlonCD** [comment]
Process hacker > deepstack.exe > Environment tab shows **CUDA_MODE** variable is empty.

**Comment by odd86** [comment]
+1 After the new release my requests take 4x more time and that is when i dont set mode to high. Now it looks like its just running on the CPU

**Comment by johnolafenwa** [comment]
Hello @VorlonCD  @odd86 
This has been fixed, get the latest release here, https://forum.deepstack.cc/t/deepstack-windows-gpu-bug-fix/624?u=john
