### ISSUE TITLE
What format are custom models expected to be in?

### ISSUE THREAD

**Issue by jasonmadigan** [johnolafenwa/DeepStack#79]
The documentation wasn't particularly clear, wondered what format are custom models expected to be in?

**Comment by robmarkcole** [comment]
The models are yolo5 format as described on https://docs.deepstack.cc/custom-models/training/index.html#important-parameters
Is this what you want to know?

**Comment by jasonmadigan** [comment]
It does, thanks @robmarkcole!

I have a use-case that's looking at some smoke detection to one of my and actually came across your other repo, which I found very helpful: https://github.com/robmarkcole/fire-detection-from-images

Have been trying to find similar models (ideally, ones easily compatible with deepstack), but which support smoke moreso than fire.

**Comment by robmarkcole** [comment]
You can just create a model for smoke in exactly the same way I've created one for fire. Lets take the conversation to https://github.com/robmarkcole/fire-detection-from-images/discussions/21
