### ISSUE TITLE
CPU usage when idle??

### ISSUE THREAD

**Issue by i00** [johnolafenwa/DeepStack#82]
I have a deepstack server running and it constantly consumes ~3% CPU when there are no requests to it ... why is this?... surely it shouldn't be doing anything?

**Comment by johnolafenwa** [comment]
Hello @i00 , while not processing requests, DeepStack polls for new requests, this loop uses some cpu.

**Comment by i00** [comment]
@johnolafenwa, why can't it just process the requests within the web request ... surely this would be much more efficient?

**Comment by somebody-somewhere-over-the-rainbow** [comment]
> 
> 
> @johnolafenwa, why can't it just process the requests within the web request ... surely this would be much more efficient?

fully agree on lower powered machines that polling can be quite heavy on the CPU...
