### ISSUE TITLE
Incompatible with Jetson Jetpack 4.5

### ISSUE THREAD

**Issue by ghost** [johnolafenwa/DeepStack#85]
Following the install guide @ https://docs.deepstack.cc/index.html it will not set up on the latest Jetpack 4.5. 4.4.1 works fine

`docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --compat32 --graphics --utility --video --display --pid=7382 /var/lib/docker/overlay2/a0759fe84523501341b99cff32ca40f0c069993705275c20533ea8749a944c9b/merged]\\\\nnvidia-container-cli: mount error: file creation failed: /var/lib/docker/overlay2/a0759fe84523501341b99cff32ca40f0c069993705275c20533ea8749a944c9b/merged/usr/lib/aarch64-linux-gnu/libnvidia-fatbinaryloader.so.440.18: file exists\\\\n\\\"\"": unknown.
ERRO[0318] error waiting for container: context canceled `

There's a thread going on and more info can be found here
https://forum.deepstack.cc/t/deepstack-release-on-jetson/506/23

**Comment by johnolafenwa** [comment]
Hello @xthedakmanx , thank you for filing this. We have released a new version to fix this, see https://forum.deepstack.cc/t/deepstack-february-2021-release-fixes-for-jetson-windows-native-and-docker-versions/724
