### ISSUE TITLE
Running two containers on Jetson

### ISSUE THREAD

**Issue by doodieb15** [johnolafenwa/DeepStack#94]
I want to do object recognition as well as face detection on a Jetson Nano 4Gb. For that I am running two containers, exposing two different ports. Object recognition works well. For face detection I can list the learned faces (none), but when I want to register a face my jetson crashes and needs to be rebooted.

What am I doing wrong? Any hints highly appreciated!

**Comment by OlafenwaMoses** [comment]
You don't need two or containers to run 2 two or more APIs. You can enable all the APIs you need in a single container. In your case, see the sample below:

```
sudo docker run --runtime nvidia -e VISION-DETECTION=True -e VISION-FACE=True  -p 80:5000 deepquestai/deepstack:jetpack
```

For more details on this, visit the link below.

https://docs.deepstack.cc/nvidia-jetson/index.html#run-with-all-apis

**Comment by doodieb15** [comment]
Thanks for the hint! Registering works now, even though the first registration takes a very long time (15min or so).
